import sys
import logging
logging.basicConfig(filename = 'kalkulator.log', level = logging.INFO, format ='%(asctime)s - %(levelname)s - %(message)s')
dane_od_użytkownika =input(("Podaj działanie,posługując się odpowiednią liczbą: 1-Dodawanie, 2-Odejmowanie, 3-Mnożenie, 4-Dzielenie:"))
liczba1 = input("Podaj składnik: 1. 2.3")
liczba2 = input("Podaj składnik: 2. 5.4")
wynik = input("Dodaję: 2.30 i 5.40")
wynik =input("Wynik to: 7.70")
wynik = input("Odejmuję: 5.40 i 2.30")
wynik = input("Wynik to: 3.10")
wynik = input("Mnożę: 2.30 i 5.40")
wynik = input("Wynik to: 12.42")
wynik =input("Dzielę: 5.40 i 2.40")
wynik = input("Wynik to: 2.25")
print(wynik)
